# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginAndRegister' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginAndRegister

  target 'LoginAndRegisterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginAndRegisterUITests' do
    # Pods for testing
  end

end
